POST http://localhost:4000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "corrola",
  "year": 1980,
  "mileage": 100000,
  "lng": 0,
  "lat": 0,
  "price": 500000
}


### PATH
Patch http://localhost:4000/reports/1
Content-Type: application/json

{
  "approved": false
}